[workspace]
authors = ["Daniel S. Roche <roche@usna.edu>"]
channels = ["conda-forge"]
name = "sparsedecomp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sage = ">=10.7,<11"
scikit-learn = ">=1.8.0,<2"
cattrs = ">=25.3.0,<26"
mypy = ">=1.19.1,<2"
plotext = ">=5.3.2,<6"
